version: '3.1'
services:
  web:
    container_name: ci-web
    build: .
    expose:
      - 5000
  nginx:
    image: "nginx:1.17.2"
    container_name: ci-nginx
    volumes:
      - ${PWD}/config/nginx:/etc/nginx
    ports:
      - 5000:80
    depends_on:
      - web